[package]
publish = false
name = "pandora-api"
version.workspace = true
edition.workspace = true

[dependencies]
pandora-types = { path = "../pandora-types" }
pandora-orchestrator = { path = "../pandora-orchestrator" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
axum.workspace = true
chrono.workspace = true
anyhow.workspace = true
