[package]
name = "pandora-provider"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

async-trait = "0.1"

tokio = {
    version = "1",
    features = ["full"]
}

tokio-util = "0.7"

serde = {
    version = "1",
    features = ["derive"]
}

thiserror = "2"

reqwest = {
    version = "0.12",
    features = ["json", "stream"]
}

serde_json = "1"

futures-util = "0.3"
