[package]
name = "pandora-security"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
pandora-docker-sandbox = { path = "../pandora-docker-sandbox" }
pandora-epistemic-sandbox = { path = "../pandora-epistemic-sandbox" }
pandora-permission = { path = "../pandora-permission" }
pandora-sandbox-governance = { path = "../pandora-sandbox-governance" }
