[package]
publish = false
name = "pandora-orchestrator"
version.workspace = true
edition.workspace = true

[dependencies]
pandora-types = { path = "../pandora-types" }
pandora-shadow-council = { path = "../pandora-shadow-council" }
pandora-services = { path = "../pandora-services" }
tokio.workspace = true
chrono.workspace = true
serde.workspace = true

anyhow.workspace = true
reqwest.workspace = true
rand.workspace = true
tracing.workspace = true
